export const items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    desc: "وصف وجبة الفطار",
    price: "50 جنية",
    cat: "فطار",
    img: "2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    desc: "وصف وجبة الغداء",
    price: "150 جنية",
    cat: "غداء",
    img: "3.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    desc: "وصف وجبة العشاء",
    price: "100 جنية",
    cat: "عشاء",
    img: "5.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ممتاز",
    desc: "وصف وجبة الغداء",
    price: "250 جنية",
    cat: "غداء",
    img: "4.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء درجة أولي",
    desc: "وصف وجبة العشاء",
    price: "200 جنية",
    cat: "عشاء",
    img: "6.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار ممتاز",
    desc: "وصف وجبة الفطار",
    price: "100 جنية",
    cat: "فطار",
    img: "1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة سناك ",
    desc: "وصف وجبة سناك",
    price: "120 جنية",
    cat: "سناك",
    img: "7.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة سناك ممتاز ",
    desc: "وصف وجبة سناك",
    price: "150 جنية",
    cat: "سناك",
    img: "7.jpg",
  },
];
